FFROM python:3.12
ENV APP /exponenta_app
WORKDIR $APP
COPY . .
CMD ["python", "exponenta_app/main.py"]

ENV APP /exponenta_app
WORKDIR $APP
COPY . .
CMD ["python", "exponenta_app/main

ENV APP /exponenta_app
WORKDIR $APP